### ISSUE TITLE
Crashing 1.12.0

### ISSUE THREAD

**Issue by sal0max** [sal0max/currencies#22]
```
2022-01-25 17:04:39.849 26446-26474/de.salomax.currencies E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: de.salomax.currencies, PID: 26446
    java.lang.AssertionError: Missing field in de.salomax.currencies.model.a
        at i2.v$l.<init>(Unknown Source:78)
        at i2.v$c.a(Unknown Source:160)
        at i2.t.f(Unknown Source:86)
        at de.salomax.currencies.model.ExchangeRatesJsonAdapter.<init>(Unknown Source:150)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at j2.b.d(Unknown Source:109)
        at i2.v$c.a(Unknown Source:145)
        at i2.t.f(Unknown Source:86)
        at i2.t.e(Unknown Source:1)
        at i2.t.c(Unknown Source:2)
        at de.salomax.currencies.repository.ExchangeRatesService.a(Unknown Source:188)
        at l2.c$a.e(Unknown Source:60)
        at c3.a.i(Unknown Source:13)
        at c6.t0.run(Unknown Source:129)
        at kotlinx.coroutines.scheduling.a.q(Unknown Source:0)
        at kotlinx.coroutines.scheduling.a$c.c(Unknown Source:14)
        at kotlinx.coroutines.scheduling.a$c.m(Unknown Source:28)
        at kotlinx.coroutines.scheduling.a$c.run(Unknown Source:0)
     Caused by: java.lang.NoSuchFieldException: EXCHANGERATE_HOST
        at java.lang.Class.getField(Class.java:1635)
        at i2.v$l.<init>(Unknown Source:32)
        at i2.v$c.a(Unknown Source:160) 
        at i2.t.f(Unknown Source:86) 
        at de.salomax.currencies.model.ExchangeRatesJsonAdapter.<init>(Unknown Source:150) 
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at j2.b.d(Unknown Source:109) 
        at i2.v$c.a(Unknown Source:145) 
        at i2.t.f(Unknown Source:86) 
        at i2.t.e(Unknown Source:1) 
        at i2.t.c(Unknown Source:2) 
        at de.salomax.currencies.repository.ExchangeRatesService.a(Unknown Source:188) 
        at l2.c$a.e(Unknown Source:60) 
        at c3.a.i(Unknown Source:13) 
        at c6.t0.run(Unknown Source:129) 
        at kotlinx.coroutines.scheduling.a.q(Unknown Source:0) 
        at kotlinx.coroutines.scheduling.a$c.c(Unknown Source:14) 
        at kotlinx.coroutines.scheduling.a$c.m(Unknown Source:28) 
        at kotlinx.coroutines.scheduling.a$c.run(Unknown Source:0) 
```

**Comment by sal0max** [comment]
fixed: 89ba81f4f866ece7e811c68d248c2c7180b115c6
